### ISSUE TITLE
Better naming for Device Token (Authentification) and Device/Token (WS Auth)

### ISSUE THREAD

**Issue by jonau** [Cross-Lab-Project/crosslab#2]
The name generation for the python api client will shorten both to DeviceToken, resulting in a naming conflict.

Can we change them to something else, like `DeviceAuthentificationToken` and `DeviceWebsocketToken` or something similiar?

**Comment by jonau** [comment]
Maybe it is wise to name the websocket endpoint the same way as the endpoint where we get the token from

**Comment by lassertos** [comment]
Changed in commit e1e0145.
