### ISSUE TITLE
Booking Service OpenAPI Spec changed

### ISSUE THREAD

**Issue by jonau** [Cross-Lab-Project/crosslab#7]
@lassertos changed openapi.json in the booking service. This is colliding with CI Operations that rebuild the file form openapi.yml. For the changes see: https://github.com/Cross-Lab-Project/crosslab/commit/8eefef85b3ce8eebfa12e00fd890717e337a74dd

Do we need to include the changes in openapi.yml?

**Comment by lassertos** [comment]
The necessary changes were applied in commits a78fd9c and effd749.
